delete from cnt_pago_anticipado;
delete from cnt_pago_anticipado_transaccion;
delete from cnt_nota_debito;
delete from cnt_nota_credito;
delete from cnt_comprobante_contable ;
delete from tb_log ;
delete from cnt_boleto;
-- delete from cnt_cliente_pasajero;
-- delete from cnt_cliente_grupo;
-- update cnt_cliente set id_cliente_grupo= null ;
delete from cnt_ingreso_caja;
-- delete from cnt_cliente;
