var data = {
    "code": 201,
    "content": [
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "ACTIVO",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentas": "1",
            "marco": "1",
            "moneda": "D",
            "nivel": 1,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 28437,
            "secuencia": 100000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "ACTIVO CORRIENTE",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1",
            "idPlanCuentas": "101",
            "marco": "1",
            "moneda": "D",
            "nivel": 2,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 28300,
            "secuencia": 200000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "DISPONIBLE",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "101",
            "idPlanCuentas": "10101",
            "marco": "1",
            "moneda": "D",
            "nivel": 3,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 21754,
            "secuencia": 300000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "CAJA CENTRAL",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "10101",
            "idPlanCuentas": "1010101",
            "marco": "1",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 18478,
            "secuencia": 400000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "CAJA",
            "fondos": 1,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1010101",
            "idPlanCuentas": "1010101001",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 18478,
            "secuencia": 500000,
            "tipo": "C"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "CAJA CHICA",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "10101",
            "idPlanCuentas": "1010102",
            "marco": "1",
            "moneda": "",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 600000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "CAJA CHICA",
            "fondos": 1,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1010102",
            "idPlanCuentas": "1010102001",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 700000,
            "tipo": "C"
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "BANCOS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "10101",
            "idPlanCuentas": "1010103",
            "marco": "1",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 3276,
            "secuencia": 800000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "BCO.BISA M/N",
            "fondos": 1,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1010103",
            "idPlanCuentas": "1010103003",
            "marco": "1",
            "moneda": "B",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 2632,
            "secuencia": 900000,
            "tipo": "B"
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "BCO.BISA M/E",
            "fondos": 1,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1010103",
            "idPlanCuentas": "1010103004",
            "marco": "1",
            "moneda": "B",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 644,
            "secuencia": 1000000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "EXIGIBLE",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "101",
            "idPlanCuentas": "10102",
            "marco": "1",
            "moneda": "D",
            "nivel": 3,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 5899,
            "secuencia": 1100000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "CLIENTES",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "10102",
            "idPlanCuentas": "1010201",
            "marco": "1",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 5899,
            "secuencia": 1200000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "cuenta": "CLIENTES POR COBRAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1010201",
            "idPlanCuentas": "1010201001",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 5899,
            "secuencia": 1300000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "PREVISION CTAS. INCOBRABLES",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1010201",
            "idPlanCuentas": "1010201002",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 1400000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "CUENTAS POR COBRAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "10102",
            "idPlanCuentas": "1010202",
            "marco": "1",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 1500000,
            "tipo": "B"
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "CUENTAS POR COBRAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1010202",
            "idPlanCuentas": "1010202003",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 1600000,
            "tipo": "B"
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "DEPOSITO EN GARANTIA",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "10102",
            "idPlanCuentas": "1010203",
            "marco": "1",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 1700000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "ALQUILER EN GARANTIA",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1010203",
            "idPlanCuentas": "1010203002",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 1800000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "TRANSITORIO",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "101",
            "idPlanCuentas": "10103",
            "marco": "1",
            "moneda": "D",
            "nivel": 3,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 646,
            "secuencia": 1900000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "ANTICIPOS AL PERSONAL",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "10103",
            "idPlanCuentas": "1010301",
            "marco": "1",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 2000000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "CUENTAS A RENDIR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "10103",
            "idPlanCuentas": "1010303",
            "marco": "1",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 2100000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201001",
            "cuenta": "CUENTA PERSONAL DE SOCIOS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "10103",
            "idPlanCuentas": "1010304",
            "marco": "1",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 2200000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "PRESTAMOS POR COBRAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "10103",
            "idPlanCuentas": "1010305",
            "marco": "1",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 646,
            "secuencia": 2300000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "PRESTAMOS AL PERSONAL",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1010305",
            "idPlanCuentas": "1010305001",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 2400000,
            "tipo": "B"
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "PRESTAMOS A PARTICULARES",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1010305",
            "idPlanCuentas": "1010305002",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 646,
            "secuencia": 2500000,
            "tipo": "B"
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "GIROS POR COBRAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "10103",
            "idPlanCuentas": "1010306",
            "marco": "1",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 2600000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "ACTIVO NO CORRIENTE",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1",
            "idPlanCuentas": "102",
            "marco": "1",
            "moneda": "D",
            "nivel": 2,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 137,
            "secuencia": 2700000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "ACTIVO FIJO",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "102",
            "idPlanCuentas": "10201",
            "marco": "1",
            "moneda": "D",
            "nivel": 3,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 2800000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "MUEBLES Y ENSERES",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "10201",
            "idPlanCuentas": "1020101",
            "marco": "1",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 2900000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "cuenta": "MUEBLES Y ENSERES",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1020101",
            "idPlanCuentas": "1020101001",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 3000000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "cuenta": "DEPREC.ACUM.MUEBLES Y ENSERES",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1020101",
            "idPlanCuentas": "1020101002",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 3100000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "EQUIPOS DE OFICINA",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "10201",
            "idPlanCuentas": "1020102",
            "marco": "1",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 3200000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "EQUIPO DE OFICINA",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1020102",
            "idPlanCuentas": "1020102001",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 3300000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "DEPREC.ACUM.EQUIPO DE OFICINA",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1020102",
            "idPlanCuentas": "1020102002",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 3400000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "EQUIPOS DE COMPUTACION",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "10201",
            "idPlanCuentas": "1020103",
            "marco": "1",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 3500000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "cuenta": "EQUIPO DE COMPUTACION",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1020103",
            "idPlanCuentas": "1020103001",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 3600000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "cuenta": "DEPREC.ACUM.EQUIPO DE COMPUTACION",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1020103",
            "idPlanCuentas": "1020103002",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 3700000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "EDIFICIOS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "10201",
            "idPlanCuentas": "1020104",
            "marco": "1",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 3800000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "cuenta": "EDIFICIOS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1020104",
            "idPlanCuentas": "1020104001",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 3900000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "cuenta": "DEPREC.ACUM.EDIFICIOS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1020104",
            "idPlanCuentas": "1020104002",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 4000000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "VEHICULOS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "10201",
            "idPlanCuentas": "1020105",
            "marco": "1",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 4100000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "VEHICULOS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1020105",
            "idPlanCuentas": "1020105001",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 4200000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "DEPREC.ACUM.VEHICULOS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1020105",
            "idPlanCuentas": "1020105002",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 4300000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "INVERSIONES",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "102",
            "idPlanCuentas": "10202",
            "marco": "1",
            "moneda": "D",
            "nivel": 3,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 4400000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "ACCIONES TELEFONICAS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "10202",
            "idPlanCuentas": "1020201",
            "marco": "1",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 4500000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "ACCIONES TELEFONICAS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1020201",
            "idPlanCuentas": "1020201001",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 4600000,
            "tipo": "B"
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "SISTEMAS CONTABLES",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "10202",
            "idPlanCuentas": "1020202",
            "marco": "1",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 4700000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "SISTEMA SIAV",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1020202",
            "idPlanCuentas": "1020202001",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 4800000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "ACTIVOS DIFERIDOS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "102",
            "idPlanCuentas": "10203",
            "marco": "1",
            "moneda": "D",
            "nivel": 3,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 137,
            "secuencia": 4900000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "ACTIVOS DIFERIDOS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "10203",
            "idPlanCuentas": "1020301",
            "marco": "1",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 137,
            "secuencia": 5000000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "SEGURO PAGADO POR ANTICIPADO",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1020301",
            "idPlanCuentas": "1020301001",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 5100000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "ALQUILERES PAGADOS POR ANTICIPADO",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1020301",
            "idPlanCuentas": "1020301002",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 5200000,
            "tipo": "B"
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "I.T.PAGADO POR ANTICIPADO",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1020301",
            "idPlanCuentas": "1020301003",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 5300000,
            "tipo": "B"
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "GASTOS DE ORGANIZACION",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1020301",
            "idPlanCuentas": "1020301004",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 5400000,
            "tipo": "B"
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020102002",
            "cuenta": "PUBLICIDAD ANTICIPADA",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1020301",
            "idPlanCuentas": "1020301005",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 137,
            "secuencia": 5500000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "INVERSIONES DE SOCIOS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "102",
            "idPlanCuentas": "10204",
            "marco": "1",
            "moneda": "D",
            "nivel": 3,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 5600000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "INVERSIONES DE SOCIOS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "10204",
            "idPlanCuentas": "1020401",
            "marco": "1",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 5700000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "INVERSIONES",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1020401",
            "idPlanCuentas": "1020401001",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 5800000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "ACTIVO INTANGIBLE",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "102",
            "idPlanCuentas": "10205",
            "marco": "1",
            "moneda": "D",
            "nivel": 3,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 5900000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "INTANGIBLES",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "10205",
            "idPlanCuentas": "1020501",
            "marco": "1",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 6000000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "DERECHO DE LLAVE",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "1020501",
            "idPlanCuentas": "1020501001",
            "marco": "1",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 6100000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "PASIVO Y PATRIMONIO",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentas": "2",
            "marco": "2",
            "moneda": "D",
            "nivel": 1,
            "presupuesto": 0,
            "rubro": "",
            "saldo": -37308,
            "secuencia": 6200000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "PASIVO",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2",
            "idPlanCuentas": "201",
            "marco": "2",
            "moneda": "D",
            "nivel": 2,
            "presupuesto": 0,
            "rubro": "",
            "saldo": -37308,
            "secuencia": 6300000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "PASIVO CORRIENTE",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "201",
            "idPlanCuentas": "20101",
            "marco": "2",
            "moneda": "D",
            "nivel": 3,
            "presupuesto": 0,
            "rubro": "",
            "saldo": -37308,
            "secuencia": 6400000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "2020301001",
            "cuenta": "LINEAS AEREAS POR PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "20101",
            "idPlanCuentas": "2010101",
            "marco": "2",
            "moneda": "",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 196,
            "secuencia": 6500000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "2020301001",
            "cuenta": "BSP-IATA M/N X PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010101",
            "idPlanCuentas": "2010101001",
            "marco": "2",
            "moneda": "B",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 6600000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "2020301001",
            "cuenta": "BSP-IATA M/E X PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010101",
            "idPlanCuentas": "2010101002",
            "marco": "2",
            "moneda": "B",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": -508,
            "secuencia": 6700000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "2020301001",
            "cuenta": "AEROCON X PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010101",
            "idPlanCuentas": "2010101003",
            "marco": "2",
            "moneda": "B",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 65,
            "secuencia": 6800000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "2020301001",
            "cuenta": "BOA X PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010101",
            "idPlanCuentas": "2010101004",
            "marco": "2",
            "moneda": "B",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 638,
            "secuencia": 6900000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "2020301001",
            "cuenta": "TAM MILITAR X PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010101",
            "idPlanCuentas": "2010101005",
            "marco": "2",
            "moneda": "B",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 7000000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "2020301001",
            "cuenta": "AEROSUR X PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010101",
            "idPlanCuentas": "2010101006",
            "marco": "2",
            "moneda": "B",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 7100000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "2020301001",
            "cuenta": "GOL X PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010101",
            "idPlanCuentas": "2010101007",
            "marco": "2",
            "moneda": "B",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 7200000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020102002",
            "cuenta": "ECO JET",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010101",
            "idPlanCuentas": "2010101008",
            "marco": "2",
            "moneda": "B",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 7300000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "2020301001",
            "cuenta": "AGENCIAS DE VIAJES POR PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "20101",
            "idPlanCuentas": "2010102",
            "marco": "2",
            "moneda": "",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": -35369,
            "secuencia": 7400000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "2020301001",
            "cuenta": "ALIANZA TRAVEL X PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010102",
            "idPlanCuentas": "2010102001",
            "marco": "2",
            "moneda": "B",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": -3377,
            "secuencia": 7500000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "2020301001",
            "cuenta": "UNIVERSAL TOURS X PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010102",
            "idPlanCuentas": "2010102002",
            "marco": "2",
            "moneda": "B",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": -3995,
            "secuencia": 7600000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "2020301001",
            "cuenta": "CHOVY TOURS X PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010102",
            "idPlanCuentas": "2010102003",
            "marco": "2",
            "moneda": "B",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": -23007,
            "secuencia": 7700000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020102002",
            "cuenta": "BOLIVIA TOURS X PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010102",
            "idPlanCuentas": "2010102004",
            "marco": "2",
            "moneda": "B",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": -4988,
            "secuencia": 7800000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "AGENCIAS MAYORISTAS POR PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "20101",
            "idPlanCuentas": "2010103",
            "marco": "2",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 126,
            "secuencia": 7900000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "2020301001",
            "cuenta": "CUARTA DIMENSION X PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010103",
            "idPlanCuentas": "2010103001",
            "marco": "2",
            "moneda": "B",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 8000000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020102002",
            "cuenta": "NACIONAL ASISTENCIA X PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010103",
            "idPlanCuentas": "2010103002",
            "marco": "2",
            "moneda": "B",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 126,
            "secuencia": 8100000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "DEPOSITOS DE CLIENTES",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "20101",
            "idPlanCuentas": "2010104",
            "marco": "2",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": -4030,
            "secuencia": 8200000,
            "tipo": "B"
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "DEPOSITO DE CLIENTES",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010104",
            "idPlanCuentas": "2010104001",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": -4030,
            "secuencia": 8300000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "IMPUESTOS POR PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "20101",
            "idPlanCuentas": "2010105",
            "marco": "2",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 8400000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "IVA POR PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010105",
            "idPlanCuentas": "2010105001",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 8500000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "I.T.POR PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010105",
            "idPlanCuentas": "2010105002",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 8600000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "cuenta": "IUE POR PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010105",
            "idPlanCuentas": "2010105003",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 8700000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "RC-IVA POR PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010105",
            "idPlanCuentas": "2010105004",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 8800000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "RETENCION DE IMPUESTOS POR PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010105",
            "idPlanCuentas": "2010105005",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 8900000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "APORTES Y RETENCIONES POR PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "20101",
            "idPlanCuentas": "2010106",
            "marco": "2",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 9000000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "FONVI POR PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010106",
            "idPlanCuentas": "2010106002",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 9100000,
            "tipo": "B"
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "AFP PREVISION BBV POR PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010106",
            "idPlanCuentas": "2010106004",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 9200000,
            "tipo": "B"
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "C.P.S. POR PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010106",
            "idPlanCuentas": "2010106005",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 9300000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "CUENTAS POR PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "20101",
            "idPlanCuentas": "2010107",
            "marco": "2",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": -648,
            "secuencia": 9400000,
            "tipo": "B"
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "DEVOLUCIONES POR PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010107",
            "idPlanCuentas": "2010107001",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 358,
            "secuencia": 9500000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "SEGUROS  POR PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010107",
            "idPlanCuentas": "2010107002",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 9600000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "PUBLICIDAD POR PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010107",
            "idPlanCuentas": "2010107003",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 186,
            "secuencia": 9700000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "CUENTAS POR PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010107",
            "idPlanCuentas": "2010107004",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 9800000,
            "tipo": "B"
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "DEVOLUCION DEP.X PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010107",
            "idPlanCuentas": "2010107007",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": -1193,
            "secuencia": 9900000,
            "tipo": "B"
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "PRESTAMOS POR PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "20101",
            "idPlanCuentas": "2010108",
            "marco": "2",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": -7251,
            "secuencia": 10000000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "PREST.MARCO A.VILLARROEL M.X PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010108",
            "idPlanCuentas": "2010108002",
            "marco": "2",
            "moneda": "B",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": -7544,
            "secuencia": 10100000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020102002",
            "cuenta": "PREST.MARIA FLORES X PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010108",
            "idPlanCuentas": "2010108003",
            "marco": "2",
            "moneda": "B",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 292,
            "secuencia": 10200000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "ALQUILERES POR PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "20101",
            "idPlanCuentas": "2010109",
            "marco": "2",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 10300000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "ALQUILER OFICINA POR PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010109",
            "idPlanCuentas": "2010109001",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 10400000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "SUELDOS DEL PERSONAL POR PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "20101",
            "idPlanCuentas": "2010111",
            "marco": "2",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 7166,
            "secuencia": 10500000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020102002",
            "cuenta": "SUE.MARCO A.VILLARROEL M.",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010111",
            "idPlanCuentas": "2010111001",
            "marco": "2",
            "moneda": "B",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 1293,
            "secuencia": 10600000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020102002",
            "cuenta": "SUE.MARIA FLORES",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010111",
            "idPlanCuentas": "2010111002",
            "marco": "2",
            "moneda": "B",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 1430,
            "secuencia": 10700000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020102002",
            "cuenta": "SUE.REYNALDO CESPEDES",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010111",
            "idPlanCuentas": "2010111003",
            "marco": "2",
            "moneda": "B",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 4443,
            "secuencia": 10800000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "CABA?AS POR PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "20101",
            "idPlanCuentas": "2010112",
            "marco": "2",
            "moneda": "",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 10900000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "COMISIONES AL PERSONAL POR PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "20101",
            "idPlanCuentas": "2010113",
            "marco": "2",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 250,
            "secuencia": 11000000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "COM.MARIA FLORES X PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010113",
            "idPlanCuentas": "2010113001",
            "marco": "2",
            "moneda": "B",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 175,
            "secuencia": 11100000,
            "tipo": "B"
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020102002",
            "cuenta": "COM.REYNALDO CESPEDES X PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010113",
            "idPlanCuentas": "2010113002",
            "marco": "2",
            "moneda": "B",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 75,
            "secuencia": 11200000,
            "tipo": "B"
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "SERVICIOS BASICOS POR PAGAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "20101",
            "idPlanCuentas": "2010114",
            "marco": "2",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 2251,
            "secuencia": 11300000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "PROV.ENERGIA ELECTRICA",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010114",
            "idPlanCuentas": "2010114001",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 954,
            "secuencia": 11400000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "PROV.TELEFONO",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010114",
            "idPlanCuentas": "2010114002",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 1233,
            "secuencia": 11500000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "PROV.ENTEL",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010114",
            "idPlanCuentas": "2010114003",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 11600000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "PROV.CONSUMO DE AGUA",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010114",
            "idPlanCuentas": "2010114004",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 11700000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "PROV.TELECEL",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010114",
            "idPlanCuentas": "2010114005",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 11800000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "PROV.INTERNET",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010114",
            "idPlanCuentas": "2010114006",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 23,
            "secuencia": 11900000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "PROV.CELULAR",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2010114",
            "idPlanCuentas": "2010114007",
            "marco": "2",
            "moneda": "B",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 40,
            "secuencia": 12000000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "PASIVO NO CORRIENTE",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "201",
            "idPlanCuentas": "20102",
            "marco": "2",
            "moneda": "D",
            "nivel": 3,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 12100000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "PREVISION P/INDEMNIZACION",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "20102",
            "idPlanCuentas": "2010201",
            "marco": "2",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 12200000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "PROVISION P/AGUINALDO NAVIDE?O",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "20102",
            "idPlanCuentas": "2010202",
            "marco": "2",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 12300000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "PATRIMONIOS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2",
            "idPlanCuentas": "202",
            "marco": "2",
            "moneda": "D",
            "nivel": 2,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 12400000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "PATRIMONIO",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "202",
            "idPlanCuentas": "20201",
            "marco": "2",
            "moneda": "D",
            "nivel": 3,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 12500000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "ACCIONES",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "20201",
            "idPlanCuentas": "2020101",
            "marco": "2",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 12600000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "RESERVAS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "202",
            "idPlanCuentas": "20202",
            "marco": "2",
            "moneda": "D",
            "nivel": 3,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 12700000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "RESERVA",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "20202",
            "idPlanCuentas": "2020201",
            "marco": "2",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 12800000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "cuenta": "RESERVA LEGAL",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2020201",
            "idPlanCuentas": "2020201001",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 12900000,
            "tipo": "B"
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "ctaItb": "3020201009",
            "cuenta": "RESERVA GENERAL",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2020201",
            "idPlanCuentas": "2020201002",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 13000000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "ACTUALIZACION DEL PATRIMONIO",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "202",
            "idPlanCuentas": "20203",
            "marco": "2",
            "moneda": "D",
            "nivel": 3,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 13100000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "AJUSTE GLOBAL AL PATRIMONIO",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "20203",
            "idPlanCuentas": "2020301",
            "marco": "2",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 13200000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "cuenta": "AJUSTE GLOBAL AL PATRIMONIO",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2020301",
            "idPlanCuentas": "2020301001",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 13300000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "RESULTADOS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "202",
            "idPlanCuentas": "20204",
            "marco": "2",
            "moneda": "D",
            "nivel": 3,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 13400000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "RESULTADOS ACUMULADOS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "20204",
            "idPlanCuentas": "2020401",
            "marco": "2",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 13500000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "cuenta": "RESULTADOS DE GESTIONES PASADAS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2020401",
            "idPlanCuentas": "2020401001",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 13600000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "cuenta": "RESULTADO DE GESTION",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "20204",
            "idPlanCuentas": "2020402",
            "marco": "2",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 13700000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 1,
            "cuenta": "RESULTADO DE LA GESTION",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "2020402",
            "idPlanCuentas": "2020402001",
            "marco": "2",
            "moneda": "D",
            "nivel": 5,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 13800000,
            "tipo": "B"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 1,
            "aplica": 0,
            "cuenta": "INGRESOS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentas": "3",
            "marco": "3",
            "moneda": "D",
            "nivel": 1,
            "presupuesto": 0,
            "rubro": "",
            "saldo": -5753,
            "secuencia": 13900000,
            "tipo": "R"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 1,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "INGRESOS OPERACIONALES",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "3",
            "idPlanCuentas": "301",
            "marco": "3",
            "moneda": "D",
            "nivel": 2,
            "presupuesto": 0,
            "rubro": "",
            "saldo": -2896,
            "secuencia": 14000000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 1,
            "aplica": 0,
            "cuenta": "INGRESOS POR VENTAS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "301",
            "idPlanCuentas": "30101",
            "marco": "3",
            "moneda": "D",
            "nivel": 3,
            "presupuesto": 0,
            "rubro": "",
            "saldo": -2896,
            "secuencia": 14100000,
            "tipo": "R"
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "2020301001",
            "cuenta": "COMISION VTA.DE BOLETOS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "30101",
            "idPlanCuentas": "3010101",
            "marco": "3",
            "moneda": "",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": -2896,
            "secuencia": 14200000,
            "tipo": ""
        },
        {
            "TGiro": 1,
            "TPasivo": 0,
            "TPresupuesto": 0,
            "aplica": 0,
            "ctaItb": "3020102002",
            "cuenta": "COMISION VENTAS MAYORISTAS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "30101",
            "idPlanCuentas": "3010102",
            "marco": "3",
            "moneda": "",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 16700000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 1,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "INGRESOS NO OPERACIONALES",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "3",
            "idPlanCuentas": "302",
            "marco": "3",
            "moneda": "D",
            "nivel": 2,
            "presupuesto": 0,
            "rubro": "",
            "saldo": -2857,
            "secuencia": 17300000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 1,
            "aplica": 0,
            "cuenta": "INGRESOS FINANCIEROS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "302",
            "idPlanCuentas": "30201",
            "marco": "3",
            "moneda": "D",
            "nivel": 3,
            "presupuesto": 0,
            "rubro": "",
            "saldo": -171,
            "secuencia": 17400000,
            "tipo": "R"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 1,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "INGRESOS BANCARIOS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "30201",
            "idPlanCuentas": "3020101",
            "marco": "3",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 17500000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 1,
            "aplica": 0,
            "cuenta": "INGRESOS PARTICULARES",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "30201",
            "idPlanCuentas": "3020102",
            "marco": "3",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": -171,
            "secuencia": 17700000,
            "tipo": "R"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 1,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "INGRESOS POR SERVICIOS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "302",
            "idPlanCuentas": "30202",
            "marco": "3",
            "moneda": "D",
            "nivel": 3,
            "presupuesto": 0,
            "rubro": "",
            "saldo": -2686,
            "secuencia": 18000000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 1,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "SERVICIOS PRESTADOS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "30202",
            "idPlanCuentas": "3020201",
            "marco": "3",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": -2686,
            "secuencia": 18100000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 1,
            "aplica": 0,
            "cuenta": "EGRESOS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentas": "4",
            "marco": "4",
            "moneda": "D",
            "nivel": 1,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 14624,
            "secuencia": 18400000,
            "tipo": "R"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 1,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "GASTOS OPERACIONALES",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "4",
            "idPlanCuentas": "401",
            "marco": "4",
            "moneda": "D",
            "nivel": 2,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 14624,
            "secuencia": 18500000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 1,
            "aplica": 0,
            "cuenta": "GASTOS ADMINISTRATIVOS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "401",
            "idPlanCuentas": "40101",
            "marco": "4",
            "moneda": "D",
            "nivel": 3,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 14461,
            "secuencia": 18600000,
            "tipo": "R"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 1,
            "aplica": 0,
            "cuenta": "GASTOS DEL PERSONAL",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "40101",
            "idPlanCuentas": "4010101",
            "marco": "4",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 771,
            "secuencia": 18700000,
            "tipo": "R"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 1,
            "aplica": 0,
            "cuenta": "SERVICIOS BASICOS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "40101",
            "idPlanCuentas": "4010102",
            "marco": "4",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 21,
            "secuencia": 19800000,
            "tipo": "R"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 1,
            "aplica": 0,
            "cuenta": "DEPRECIACION ACTIVO FIJO",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "40101",
            "idPlanCuentas": "4010103",
            "marco": "4",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 20500000,
            "tipo": "R"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 1,
            "aplica": 0,
            "cuenta": "GASTOS GENERALES",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "40101",
            "idPlanCuentas": "4010104",
            "marco": "4",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 13447,
            "secuencia": 21100000,
            "tipo": "R"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 1,
            "aplica": 0,
            "cuenta": "APORTES PATRONALES",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "40101",
            "idPlanCuentas": "4010105",
            "marco": "4",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 22500000,
            "tipo": "R"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 1,
            "aplica": 0,
            "cuenta": "MANTENIMIENTO Y REPARACION",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "40101",
            "idPlanCuentas": "4010106",
            "marco": "4",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 219,
            "secuencia": 23000000,
            "tipo": "R"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 1,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "GASTOS OPERATIVOS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "401",
            "idPlanCuentas": "40102",
            "marco": "4",
            "moneda": "D",
            "nivel": 3,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 163,
            "secuencia": 23500000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 1,
            "aplica": 0,
            "cuenta": "IMPUESTOS Y PATENTES",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "40102",
            "idPlanCuentas": "4010201",
            "marco": "4",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 1,
            "secuencia": 23600000,
            "tipo": "R"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 1,
            "aplica": 0,
            "cuenta": "GASTOS DE COMERCIALIZACION",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "40102",
            "idPlanCuentas": "4010203",
            "marco": "4",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 162,
            "secuencia": 24700000,
            "tipo": "R"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 1,
            "aplica": 0,
            "cuenta": "GASTOS FINANCIEROS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "401",
            "idPlanCuentas": "40103",
            "marco": "4",
            "moneda": "D",
            "nivel": 3,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 25600000,
            "tipo": "R"
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 1,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "GASTOS BANCARIOS",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "40103",
            "idPlanCuentas": "4010301",
            "marco": "4",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 25700000,
            "tipo": ""
        },
        {
            "TGiro": 0,
            "TPasivo": 0,
            "TPresupuesto": 1,
            "aplica": 0,
            "ctaItb": "3020201009",
            "cuenta": "GASTOS FINANCIEROS PARTICULARES",
            "fondos": 0,
            "idEmpresa": 1,
            "idPlanCuentaPadre": "40103",
            "idPlanCuentas": "4010302",
            "marco": "4",
            "moneda": "D",
            "nivel": 4,
            "presupuesto": 0,
            "rubro": "",
            "saldo": 0,
            "secuencia": 26200000,
            "tipo": ""
        }
    ]
};